import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { map } from 'rxjs/operators';
import { CountryMapperService } from './country-mapper.service';
import { CountryModel } from './models/country.model';

@Injectable({
  providedIn: 'root',
})
export class CountriesService {
  constructor(private countryMapperService: CountryMapperService) {}

  get(): Observable<CountryModel[]> {
    return of([
      {
        name: 'Afghanistan',
        topLevelDomain: ['.af'],
        alpha2Code: 'AF',
        alpha3Code: 'AFG',
        callingCodes: ['93'],
        capital: 'Kabul',
        altSpellings: ['AF', 'Afġānistān'],
        region: 'Asia',
        subregion: 'Southern Asia',
        population: 27657145,
        latlng: [33.0, 65.0],
        demonym: 'Afghan',
        area: 652230.0,
        gini: 27.8,
        timezones: ['UTC+04:30'],
        borders: ['IRN', 'PAK', 'TKM', 'UZB', 'TJK', 'CHN'],
        nativeName: 'افغانستان',
        numericCode: '004',
      },
      {
        name: 'Åland Islands',
        topLevelDomain: ['.ax'],
        alpha2Code: 'AX',
        alpha3Code: 'ALA',
        callingCodes: ['358'],
        capital: 'Mariehamn',
        altSpellings: ['AX', 'Aaland', 'Aland', 'Ahvenanmaa'],
        region: 'Europe',
        subregion: 'Northern Europe',
        population: 28875,
        latlng: [60.116667, 19.9],
        demonym: 'Ålandish',
        area: 1580.0,
        gini: null,
        timezones: ['UTC+02:00'],
        borders: [],
        nativeName: 'Åland',
        numericCode: '248',
      },
      {
        name: 'Albania',
        topLevelDomain: ['.al'],
        alpha2Code: 'AL',
        alpha3Code: 'ALB',
        callingCodes: ['355'],
        capital: 'Tirana',
        altSpellings: ['AL', 'Shqipëri', 'Shqipëria', 'Shqipnia'],
        region: 'Europe',
        subregion: 'Southern Europe',
        population: 2886026,
        latlng: [41.0, 20.0],
        demonym: 'Albanian',
        area: 28748.0,
        gini: 34.5,
        timezones: ['UTC+01:00'],
        borders: ['MNE', 'GRC', 'MKD', 'KOS'],
        nativeName: 'Shqipëria',
        numericCode: '008',
      },
      {
        name: 'Algeria',
        topLevelDomain: ['.dz'],
        alpha2Code: 'DZ',
        alpha3Code: 'DZA',
        callingCodes: ['213'],
        capital: 'Algiers',
        altSpellings: ['DZ', 'Dzayer', 'Algérie'],
        region: 'Africa',
        subregion: 'Northern Africa',
        population: 40400000,
        latlng: [28.0, 3.0],
        demonym: 'Algerian',
        area: 2381741.0,
        gini: 35.3,
        timezones: ['UTC+01:00'],
        borders: ['TUN', 'LBY', 'NER', 'ESH', 'MRT', 'MLI', 'MAR'],
        nativeName: 'الجزائر',
        numericCode: '012',
      },
      {
        name: 'American Samoa',
        topLevelDomain: ['.as'],
        alpha2Code: 'AS',
        alpha3Code: 'ASM',
        callingCodes: ['1684'],
        capital: 'Pago Pago',
        altSpellings: ['AS', 'Amerika Sāmoa', 'Amelika Sāmoa', 'Sāmoa Amelika'],
        region: 'Oceania',
        subregion: 'Polynesia',
        population: 57100,
        latlng: [-14.33333333, -170.0],
        demonym: 'American Samoan',
        area: 199.0,
        gini: null,
        timezones: ['UTC-11:00'],
        borders: [],
        nativeName: 'American Samoa',
        numericCode: '016',
      },
      {
        name: 'Andorra',
        topLevelDomain: ['.ad'],
        alpha2Code: 'AD',
        alpha3Code: 'AND',
        callingCodes: ['376'],
        capital: 'Andorra la Vella',
        altSpellings: ['AD', 'Principality of Andorra', "Principat d'Andorra"],
        region: 'Europe',
        subregion: 'Southern Europe',
        population: 78014,
        latlng: [42.5, 1.5],
        demonym: 'Andorran',
        area: 468.0,
        gini: null,
        timezones: ['UTC+01:00'],
        borders: ['FRA', 'ESP'],
        nativeName: 'Andorra',
        numericCode: '020',
      },
      {
        name: 'Angola',
        topLevelDomain: ['.ao'],
        alpha2Code: 'AO',
        alpha3Code: 'AGO',
        callingCodes: ['244'],
        capital: 'Luanda',
        altSpellings: ['AO', 'República de Angola', "ʁɛpublika de an'ɡɔla"],
        region: 'Africa',
        subregion: 'Middle Africa',
        population: 25868000,
        latlng: [-12.5, 18.5],
        demonym: 'Angolan',
        area: 1246700.0,
        gini: 58.6,
        timezones: ['UTC+01:00'],
        borders: ['COG', 'COD', 'ZMB', 'NAM'],
        nativeName: 'Angola',
        numericCode: '024',
      },
      {
        name: 'Anguilla',
        topLevelDomain: ['.ai'],
        alpha2Code: 'AI',
        alpha3Code: 'AIA',
        callingCodes: ['1264'],
        capital: 'The Valley',
        altSpellings: ['AI'],
        region: 'Americas',
        subregion: 'Caribbean',
        population: 13452,
        latlng: [18.25, -63.16666666],
        demonym: 'Anguillian',
        area: 91.0,
        gini: null,
        timezones: ['UTC-04:00'],
        borders: [],
        nativeName: 'Anguilla',
        numericCode: '660',
      },
      {
        name: 'Antarctica',
        topLevelDomain: ['.aq'],
        alpha2Code: 'AQ',
        alpha3Code: 'ATA',
        callingCodes: ['672'],
        capital: '',
        altSpellings: [],
        region: 'Polar',
        subregion: '',
        population: 1000,
        latlng: [-74.65, 4.48],
        demonym: '',
        area: 1.4e7,
        gini: null,
        timezones: [
          'UTC-03:00',
          'UTC+03:00',
          'UTC+05:00',
          'UTC+06:00',
          'UTC+07:00',
          'UTC+08:00',
          'UTC+10:00',
          'UTC+12:00',
        ],
        borders: [],
        nativeName: 'Antarctica',
        numericCode: '010',
      },
      {
        name: 'Antigua and Barbuda',
        topLevelDomain: ['.ag'],
        alpha2Code: 'AG',
        alpha3Code: 'ATG',
        callingCodes: ['1268'],
        capital: "Saint John's",
        altSpellings: ['AG'],
        region: 'Americas',
        subregion: 'Caribbean',
        population: 86295,
        latlng: [17.05, -61.8],
        demonym: 'Antiguan, Barbudan',
        area: 442.0,
        gini: null,
        timezones: ['UTC-04:00'],
        borders: [],
        nativeName: 'Antigua and Barbuda',
        numericCode: '028',
      },
    ]).pipe(map((countries) => this.countryMapperService.toClient(countries)));
  }
}
